=== godotengine/godot/doc/class.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="class">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="brief_description" />
				<xs:element type="xs:string" name="description" />
				<xs:element name="tutorials">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="link" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="title" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="constructors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constructor" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="rest_param" maxOccurs="1" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="methods" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="method" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="returns_error" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="number" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="rest_param" maxOccurs="1" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
									<!-- deprecated -->
									<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
									<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
									<!-- /deprecated -->
									<xs:attribute type="xs:string" name="deprecated" use="optional" />
									<xs:attribute type="xs:string" name="experimental" use="optional" />
									<xs:attribute type="xs:string" name="keywords" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="members" minOccurs="0">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded" minOccurs="0">
							<xs:element name="member">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="type" />
											<xs:attribute type="xs:string" name="setter" />
											<xs:attribute type="xs:string" name="getter" />
											<xs:attribute type="xs:string" name="overrides" use="optional" />
											<xs:attribute type="xs:string" name="enum" use="optional" />
											<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											<xs:attribute type="xs:string" name="default" use="optional" />
											<!-- deprecated -->
											<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
											<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
											<!-- /deprecated -->
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="signals" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="signal" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="keywords" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="rest_param" maxOccurs="1" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<!-- deprecated -->
									<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
									<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
									<!-- /deprecated -->
									<xs:attribute type="xs:string" name="deprecated" use="optional" />
									<xs:attribute type="xs:string" name="experimental" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="constants" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constant" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="value" />
											<xs:attribute type="xs:string" name="enum" use="optional" />
											<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											<!-- deprecated -->
											<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
											<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
											<!-- /deprecated -->
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="annotations" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="annotation" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="rest_param" maxOccurs="1" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
									<xs:attribute type="xs:string" name="keywords" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="theme_items" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="theme_item" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="data_type" />
											<xs:attribute type="xs:string" name="type" />
											<xs:attribute type="xs:string" name="default" use="optional" />
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="operators" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="operator" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:string" name="name" />
			<xs:attribute type="xs:string" name="inherits" use="optional" />
			<xs:attribute type="xs:string" name="api_type" use="optional" />
			<!-- deprecated -->
			<xs:attribute type="xs:float" name="version" use="optional" />
			<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
			<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
			<!-- /deprecated -->
			<xs:attribute type="xs:string" name="deprecated" use="optional" />
			<xs:attribute type="xs:string" name="experimental" use="optional" />
			<xs:attribute type="xs:string" name="keywords" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== godotengine/godot/doc/classes/EditorScenePostImportPlugin.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="EditorScenePostImportPlugin" inherits="RefCounted" api_type="editor" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
		Plugin to control and modifying the process of importing a scene.
	</brief_description>
	<description>
		This plugin type exists to modify the process of importing scenes, allowing to change the content as well as add importer options at every stage of the process.
	</description>
	<tutorials>
	</tutorials>
	<methods>
		<method name="_get_import_options" qualifiers="virtual">
			<return type="void" />
			<param index="0" name="path" type="String" />
			<description>
				Override to add general import options. These will appear in the main import dock on the editor. Add options via [method add_import_option] and [method add_import_option_advanced].
			</description>
		</method>
		<method name="_get_internal_import_options" qualifiers="virtual">
			<return type="void" />
			<param index="0" name="category" type="int" />
			<description>
				Override to add internal import options. These will appear in the 3D scene import dialog. Add options via [method add_import_option] and [method add_import_option_advanced].
			</description>
		</method>
		<method name="_get_internal_option_update_view_required" qualifiers="virtual const">
			<return type="Variant" />
			<param index="0" name="category" type="int" />
			<param index="1" name="option" type="String" />
			<description>
				Should return [code]true[/code] if the 3D view of the import dialog needs to update when changing the given option.
			</description>
		</method>
		<method name="_get_internal_option_visibility" qualifiers="virtual const">
			<return type="Variant" />
			<param index="0" name="category" type="int" />
			<param index="1" name="for_animation" type="bool" />
			<param index="2" name="option" type="String" />
			<description>
				Should return [code]true[/code] to show the given option, [code]false[/code] to hide the given option, or [code]null[/code] to ignore.
			</description>
		</method>
		<method name="_get_option_visibility" qualifiers="virtual const">
			<return type="Variant" />
			<param index="0" name="path" type="String" />
			<param index="1" name="for_animation" type="bool" />
			<param index="2" name="option" type="String" />
			<description>
				Should return [code]true[/code] to show the given option, [code]false[/code] to hide the given option, or [code]null[/code] to ignore.
			</description>
		</method>
		<method name="_internal_process" qualifiers="virtual">
			<return type="void" />
			<param index="0" name="category" type="int" />
			<param index="1" name="base_node" type="Node" />
			<param index="2" name="node" type="Node" />
			<param index="3" name="resource" type="Resource" />
			<description>
				Process a specific node or resource for a given category.
			</description>
		</method>
		<method name="_post_process" qualifiers="virtual">
			<return type="void" />
			<param index="0" name="scene" type="Node" />
			<description>
				Post-process the scene. This function is called after the final scene has been configured.
			</description>
		</method>
		<method name="_pre_process" qualifiers="virtual">
			<return type="void" />
			<param index="0" name="scene" type="Node" />
			<description>
				Pre-process the scene. This function is called right after the scene format loader loads the scene and no changes have been made.
				Pre-process may be used to adjust internal import options in the [code]"nodes"[/code], [code]"meshes"[/code], [code]"animations"[/code] or [code]"materials"[/code] keys inside [code]get_option_value("_subresources")[/code].
			</description>
		</method>
		<method name="add_import_option">
			<return type="void" />
			<param index="0" name="name" type="String" />
			<param index="1" name="value" type="Variant" />
			<description>
				Add a specific import option (name and default value only). This function can only be called from [method _get_import_options] and [method _get_internal_import_options].
			</description>
		</method>
		<method name="add_import_option_advanced">
			<return type="void" />
			<param index="0" name="type" type="int" enum="Variant.Type" />
			<param index="1" name="name" type="String" />
			<param index="2" name="default_value" type="Variant" />
			<param index="3" name="hint" type="int" enum="PropertyHint" default="0" />
			<param index="4" name="hint_string" type="String" default="&quot;&quot;" />
			<param index="5" name="usage_flags" type="int" default="6" />
			<description>
				Add a specific import option. This function can only be called from [method _get_import_options] and [method _get_internal_import_options].
			</description>
		</method>
		<method name="get_option_value" qualifiers="const">
			<return type="Variant" />
			<param index="0" name="name" type="StringName" />
			<description>
				Query the value of an option. This function can only be called from those querying visibility, or processing.
			</description>
		</method>
	</methods>
	<constants>
		<constant name="INTERNAL_IMPORT_CATEGORY_NODE" value="0" enum="InternalImportCategory">
		</constant>
		<constant name="INTERNAL_IMPORT_CATEGORY_MESH_3D_NODE" value="1" enum="InternalImportCategory">
		</constant>
		<constant name="INTERNAL_IMPORT_CATEGORY_MESH" value="2" enum="InternalImportCategory">
		</constant>
		<constant name="INTERNAL_IMPORT_CATEGORY_MATERIAL" value="3" enum="InternalImportCategory">
		</constant>
		<constant name="INTERNAL_IMPORT_CATEGORY_ANIMATION" value="4" enum="InternalImportCategory">
		</constant>
		<constant name="INTERNAL_IMPORT_CATEGORY_ANIMATION_NODE" value="5" enum="InternalImportCategory">
		</constant>
		<constant name="INTERNAL_IMPORT_CATEGORY_SKELETON_3D_NODE" value="6" enum="InternalImportCategory">
		</constant>
		<constant name="INTERNAL_IMPORT_CATEGORY_MAX" value="7" enum="InternalImportCategory">
		</constant>
	</constants>
</class>

=== godotengine/godot/modules/csg_2d/doc_classes/CSGCapsule2D.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="CSGCapsule2D" inherits="CSGPrimitive2D" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../doc/class.xsd">
	<brief_description>
		A 2D CSG Capsule shape.
	</brief_description>
	<description>
		This node allows creating a capsule for use with the 2D CSG system.
		[b]Performance:[/b] CSG nodes are only intended for prototyping as they have a significant CPU performance cost. Consider baking final CSG operation results into static geometry that replaces the CSG nodes. This can be done using the various [b]Bake[/b] options available in the [b]CSG2D[/b] menu at the top of the 2D editor viewport after selecting a 2D CSG node.
	</description>
	<tutorials>
	</tutorials>
	<members>
		<member name="height" type="float" setter="set_height" getter="get_height" default="30.0">
			The height of the capsule.
		</member>
		<member name="radial_segments" type="int" setter="set_radial_segments" getter="get_radial_segments" default="6">
			Number of radial segments on each quarter circle of the capsule.
		</member>
		<member name="radius" type="float" setter="set_radius" getter="get_radius" default="10.0">
			The radius of the capsule.
		</member>
	</members>
</class>

=== godotengine/godot/doc/classes/EditorToast.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="EditorToast" inherits="PanelContainer" api_type="editor" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
		Alert notification that is displayed in the Editor.
	</brief_description>
	<description>
		Used in conjunction with [EditorToaster], this class represents an individual toast notification that can be displayed within the editor. To obtain an instance, see [method EditorToaster.push_toast].
	</description>
	<tutorials>
	</tutorials>
	<methods>
		<method name="add_action">
			<return type="Button" />
			<param index="0" name="action" type="String" />
			<param index="1" name="callback" type="Callable" />
			<param index="2" name="icon" type="StringName" default="&amp;&quot;&quot;" />
			<description>
				Sets an action button on the toast notification with the specified label, callback function, and optional icon. When the action button is clicked, the provided callback function will be executed.
				[codeblock]
				func _ready():
					var toast = EditorInterface.get_editor_toaster().push_toast("Click on each button to open their documentation page!")
					toast.add_action("Open 2D Documentation", _2d_docs.bind(toast), "Node2D")
					toast.add_action("Open 3D Documentation", _3d_docs.bind(toast), "Node3D")

				func _2d_docs(toast):
					EditorInterface.get_script_editor().goto_help("class_name:Node2D")
					toast.close()

				func _3d_docs(toast):
					EditorInterface.get_script_editor().goto_help("class_name:Node3D")
					toast.close()
				[/codeblock]
				This will add two action buttons to the toast notification. Clicking on each button will open the corresponding documentation page for 2D and 3D nodes, respectively, and then close the toast.
				[b]Note:[/b] The method returns the [Button] instance, allowing for further customization of the action button.
			</description>
		</method>
		<method name="close">
			<return type="void" />
			<param index="0" name="instant" type="bool" default="false" />
			<description>
				Closes the toast notification. If [param instant] is [code]false[/code], the toast disappears with a fade-out effect.
			</description>
		</method>
		<method name="copy" qualifiers="const">
			<return type="void" />
			<description>
				Copies the toast's message to the clipboard.
			</description>
		</method>
		<method name="get_message" qualifiers="const">
			<return type="String" />
			<description>
				Returns the message displayed in the toast notification.
			</description>
		</method>
		<method name="get_severity" qualifiers="const">
			<return type="int" enum="EditorToaster.Severity" />
			<description>
				Returns the severity level of the toast notification.
			</description>
		</method>
	</methods>
</class>

=== godotengine/godot/modules/openxr/doc_classes/OpenXRDpadBindingModifier.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="OpenXRDpadBindingModifier" inherits="OpenXRBindingModifier" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../doc/class.xsd">
	<brief_description>
		The DPad binding modifier converts an axis input to a dpad output.
	</brief_description>
	<description>
		The DPad binding modifier converts an axis input to a dpad output. New input paths for each dpad direction will be added to the interaction profile.
		See [url=https://registry.khronos.org/OpenXR/specs/1.1/html/xrspec.html#XR_EXT_dpad_binding]XR_EXT_dpad_binding[/url] for indepth details.
	</description>
	<tutorials>
	</tutorials>
	<members>
		<member name="action_set" type="OpenXRActionSet" setter="set_action_set" getter="get_action_set">
			Action set for which this dpad binding modifier is active.
		</member>
		<member name="center_region" type="float" setter="set_center_region" getter="get_center_region" default="0.1">
			Center region in which our center position of our dpad return [code]true[/code].
		</member>
		<member name="input_path" type="String" setter="set_input_path" getter="get_input_path" default="&quot;&quot;">
			Input path for this dpad binding modifier.
		</member>
		<member name="is_sticky" type="bool" setter="set_is_sticky" getter="get_is_sticky" default="false">
			If [code]false[/code], when the joystick enters a new dpad zone this becomes true.
			If [code]true[/code], when the joystick remains in active dpad zone, this remains true even if we overlap with another zone.
		</member>
		<member name="threshold" type="float" setter="set_threshold" getter="get_threshold" default="0.4">
			When our input value is equal or larger than this value, our dpad in that direction becomes true. It stays true until it falls under the [member threshold_released] value.
		</member>
		<member name="threshold_released" type="float" setter="set_threshold_released" getter="get_threshold_released" default="0.4">
			When our input value falls below this, our output becomes false.
		</member>
		<member name="wedge_angle" type="float" setter="set_wedge_angle" getter="get_wedge_angle" default="1.5708">
		</member>
	</members>
</class>

=== godotengine/godot/doc/classes/PhysicsShapeCollisionResult3D.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="PhysicsShapeCollisionResult3D" inherits="RefCounted" api_type="core" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
		Stores the collision points of a shape intersection query.
	</brief_description>
	<description>
		This class contains the contact points computed by [method PhysicsDirectSpaceState3D.collide_shape_typed].
		Each collision is represented as a pair of points: one on the queried shape and one on the colliding shape.
	</description>
	<tutorials>
	</tutorials>
	<methods>
		<method name="get_collision_point_on_colliding_shape" qualifiers="const">
			<return type="Vector3" />
			<param index="0" name="collision_index" type="int" default="0" />
			<description>
				Returns the collision point on the colliding shape for the collision at the given index.
			</description>
		</method>
		<method name="get_collision_point_on_queried_shape" qualifiers="const">
			<return type="Vector3" />
			<param index="0" name="collision_index" type="int" default="0" />
			<description>
				Returns the collision point on the queried shape for the collision at the given index.
			</description>
		</method>
	</methods>
	<members>
		<member name="collision_count" type="int" setter="" getter="get_collision_count" default="0">
			The number of shapes that collide with the queried shape.
		</member>
		<member name="max_collisions" type="int" setter="set_max_collisions" getter="get_max_collisions" default="32">
			The maximum number of collisions this object can store.
		</member>
	</members>
</class>
