=== godotengine/godot/doc/class.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="class">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="brief_description" />
				<xs:element type="xs:string" name="description" />
				<xs:element name="tutorials">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="link" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="title" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="constructors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constructor" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="rest_param" maxOccurs="1" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="methods" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="method" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="returns_error" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="number" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="rest_param" maxOccurs="1" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
									<!-- deprecated -->
									<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
									<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
									<!-- /deprecated -->
									<xs:attribute type="xs:string" name="deprecated" use="optional" />
									<xs:attribute type="xs:string" name="experimental" use="optional" />
									<xs:attribute type="xs:string" name="keywords" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="members" minOccurs="0">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded" minOccurs="0">
							<xs:element name="member">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="type" />
											<xs:attribute type="xs:string" name="setter" />
											<xs:attribute type="xs:string" name="getter" />
											<xs:attribute type="xs:string" name="overrides" use="optional" />
											<xs:attribute type="xs:string" name="enum" use="optional" />
											<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											<xs:attribute type="xs:string" name="default" use="optional" />
											<!-- deprecated -->
											<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
											<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
											<!-- /deprecated -->
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="signals" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="signal" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="keywords" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="rest_param" maxOccurs="1" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<!-- deprecated -->
									<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
									<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
									<!-- /deprecated -->
									<xs:attribute type="xs:string" name="deprecated" use="optional" />
									<xs:attribute type="xs:string" name="experimental" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="constants" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constant" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="value" />
											<xs:attribute type="xs:string" name="enum" use="optional" />
											<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											<!-- deprecated -->
											<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
											<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
											<!-- /deprecated -->
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="annotations" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="annotation" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="rest_param" maxOccurs="1" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
									<xs:attribute type="xs:string" name="keywords" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="theme_items" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="theme_item" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="data_type" />
											<xs:attribute type="xs:string" name="type" />
											<xs:attribute type="xs:string" name="default" use="optional" />
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="operators" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="operator" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:string" name="name" />
			<xs:attribute type="xs:string" name="inherits" use="optional" />
			<xs:attribute type="xs:string" name="api_type" use="optional" />
			<!-- deprecated -->
			<xs:attribute type="xs:float" name="version" use="optional" />
			<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
			<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
			<!-- /deprecated -->
			<xs:attribute type="xs:string" name="deprecated" use="optional" />
			<xs:attribute type="xs:string" name="experimental" use="optional" />
			<xs:attribute type="xs:string" name="keywords" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== godotengine/godot/modules/openxr/doc_classes/OpenXRFutureExtension.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="OpenXRFutureExtension" inherits="OpenXRExtensionWrapper" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../doc/class.xsd">
	<brief_description>
		The OpenXR Future extension allows for asynchronous APIs to be used.
	</brief_description>
	<description>
		This is a support extension in OpenXR that allows other OpenXR extensions to start asynchronous functions and get a callback after this function finishes. It is not intended for consumption within GDScript but can be accessed from GDExtension.
	</description>
	<tutorials>
	</tutorials>
	<methods>
		<method name="cancel_future">
			<return type="void" />
			<param index="0" name="future" type="int" />
			<description>
				Cancel an in-progress future. [param future] must be a [code]XrFutureEXT[/code] value previously returned by an API that started an asynchronous function.
			</description>
		</method>
		<method name="get_active" qualifiers="const">
			<return type="bool" />
			<description>
				Returns [code]true[/code] if futures are available in the OpenXR runtime used. This function will only return a usable result after OpenXR has been initialized.
			</description>
		</method>
		<method name="register_future">
			<return type="void" />
			<param index="0" name="future" type="int" />
			<param index="1" name="callable" type="Callable" />
			<description>
				Register the [param callable] to invoke after a future completes processing. [param future] must be a [code]XrFutureEXT[/code] value previously returned by an API that started an asynchronous function.
			</description>
		</method>
	</methods>
</class>

=== godotengine/godot/doc/classes/MultiMeshInstance3D.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="MultiMeshInstance3D" inherits="GeometryInstance3D" version="4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
		Node that instances a [MultiMesh].
	</brief_description>
	<description>
		[MultiMeshInstance3D] is a specialized node to instance [GeometryInstance3D]s based on a [MultiMesh] resource.
		This is useful to optimize the rendering of a high amount of instances of a given mesh (for example trees in a forest or grass strands).
	</description>
	<tutorials>
		<link title="Animating thousands of fish with MultiMeshInstance">https://docs.godotengine.org/en/latest/tutorials/3d/vertex_animation/animating_thousands_of_fish.html</link>
		<link title="Using MultiMeshInstance">https://docs.godotengine.org/en/latest/tutorials/3d/using_multi_mesh_instance.html</link>
		<link title="Optimization using MultiMeshes">https://docs.godotengine.org/en/latest/tutorials/optimization/using_multimesh.html</link>
	</tutorials>
	<methods>
	</methods>
	<members>
		<member name="multimesh" type="MultiMesh" setter="set_multimesh" getter="get_multimesh">
			The [MultiMesh] resource that will be used and shared among all instances of the [MultiMeshInstance3D].
		</member>
	</members>
	<constants>
	</constants>
</class>

=== godotengine/godot/doc/classes/MicrophoneFeed.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="MicrophoneFeed" inherits="RefCounted" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
		A microphone feed gives you access to a single physical microphone attached to your device.
	</brief_description>
	<description>
		A microphone feed gives you access to a single physical microphone attached to your device.
		When enabled, Godot will start acquiring stereo sample frames at the [method AudioServer.get_input_mix_rate]
		and writing them into an internal buffer of size [method get_input_buffer_size].
	</description>
	<tutorials>
	</tutorials>
	<methods>
		<method name="get_buffer_length_frames">
			<return type="int" />
			<description>
				Returns the absolute size of the microphone input buffer.
				This is set as some multiple of the audio latency and can be used to
				estimate the minimum rate at which the frames are fetched.
			</description>
		</method>
		<method name="get_frames">
			<return type="PackedVector2Array" />
			<param index="0" name="frames" type="int" />
			<description>
				Gets the next [param frames] audio samples from the internal microphone buffer.
				The buffer is filled at the rate of [method AudioServer.get_input_mix_rate] frames per second when [param feed_is_active] is true.
				Returns a [PackedVector2Array] containing exactly [param frames] audio samples if available, or an empty [PackedVector2Array].
				The samples are signed floating-point PCM between [code]-1[/code] and [code]1[/code]. You will have to scale them if you want to use them as 8 or 16-bit integer samples. ([code]v = 0x7fff * samples[0].x[/code])
			</description>
		</method>
		<method name="get_frames_available">
			<return type="int" />
			<description>
				Returns the number of frames available to read using [method get_frames].
			</description>
		</method>
		<method name="get_name" qualifiers="const">
			<return type="String" />
			<description>
				Returns the microphone's name.
			</description>
		</method>
		<method name="set_name">
			<return type="void" />
			<param index="0" name="name" type="String" />
			<description>
				Sets the microphone's name.
			</description>
		</method>
	</methods>
	<members>
		<member name="feed_is_active" type="bool" setter="set_active" getter="is_active" default="false">
			If [code]true[/code], the microphone feed is active.
		</member>
	</members>
</class>

=== godotengine/godot/modules/visual_script/doc_classes/VisualScriptPropertyGet.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="VisualScriptPropertyGet" inherits="VisualScriptNode" version="4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../doc/class.xsd">
	<brief_description>
	</brief_description>
	<description>
	</description>
	<tutorials>
	</tutorials>
	<methods>
	</methods>
	<members>
		<member name="base_script" type="String" setter="set_base_script" getter="get_base_script">
		</member>
		<member name="base_type" type="StringName" setter="set_base_type" getter="get_base_type" default="@&quot;Object&quot;">
		</member>
		<member name="basic_type" type="int" setter="set_basic_type" getter="get_basic_type" enum="Variant.Type">
		</member>
		<member name="index" type="StringName" setter="set_index" getter="get_index">
		</member>
		<member name="node_path" type="NodePath" setter="set_base_path" getter="get_base_path">
		</member>
		<member name="property" type="StringName" setter="set_property" getter="get_property" default="@&quot;&quot;">
		</member>
		<member name="set_mode" type="int" setter="set_call_mode" getter="get_call_mode" enum="VisualScriptPropertyGet.CallMode" default="0">
		</member>
	</members>
	<constants>
		<constant name="CALL_MODE_SELF" value="0" enum="CallMode">
		</constant>
		<constant name="CALL_MODE_NODE_PATH" value="1" enum="CallMode">
		</constant>
		<constant name="CALL_MODE_INSTANCE" value="2" enum="CallMode">
		</constant>
	</constants>
</class>

=== godotengine/godot/doc/classes/CanvasGroup.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="CanvasGroup" inherits="Node2D" api_type="core" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
		Merges several 2D nodes into a single draw operation.
	</brief_description>
	<description>
		Child [CanvasItem] nodes of a [CanvasGroup] are drawn as a single object. It allows to e.g. draw overlapping translucent 2D nodes without causing the overlapping sections to be more opaque than intended (set the [member CanvasItem.self_modulate] property on the [CanvasGroup] to achieve this effect).
		[b]Note:[/b] The [CanvasGroup] uses a custom shader to read from the backbuffer to draw its children. Assigning a [Material] to the [CanvasGroup] overrides the built-in shader. To duplicate the behavior of the built-in shader in a custom [Shader], use the following:
		[codeblock]
		shader_type canvas_item;
		render_mode unshaded;

		uniform sampler2D screen_texture : hint_screen_texture, repeat_disable, filter_nearest;

		void fragment() {
			vec4 c = textureLod(screen_texture, SCREEN_UV, 0.0);

			if (c.a &gt; 0.0001) {
				c.rgb /= c.a;
			}

			COLOR *= c;
		}
		[/codeblock]
		[b]Note:[/b] Since [CanvasGroup] and [member CanvasItem.clip_children] both utilize the backbuffer, children of a [CanvasGroup] who have their [member CanvasItem.clip_children] set to anything other than [constant CanvasItem.CLIP_CHILDREN_DISABLED] will not function correctly.
		[b]Performance:[/b] Rendering a [CanvasGroup] is faster than rendering an additional [Viewport]. However, rendering a [CanvasGroup] still has a performance impact comparing to rendering sprites directly, as it still switches render targets. This comes with a performance penalty on mobile and some integrated GPUs.
	</description>
	<tutorials>
	</tutorials>
	<members>
		<member name="clear_margin" type="float" setter="set_clear_margin" getter="get_clear_margin" default="10.0">
			Sets the size of the margin used to expand the clearing rect of this [CanvasGroup]. This expands the area of the backbuffer that will be used by the [CanvasGroup]. A smaller margin will reduce the area of the backbuffer used which can increase performance, however if [member use_mipmaps] is enabled, a small margin may result in mipmap errors at the edge of the [CanvasGroup]. Accordingly, this should be left as small as possible, but should be increased if artifacts appear along the edges of the canvas group.
		</member>
		<member name="fit_margin" type="float" setter="set_fit_margin" getter="get_fit_margin" default="10.0">
			Sets the size of a margin used to expand the drawable rect of this [CanvasGroup]. The size of the [CanvasGroup] is determined by fitting a rect around its children then expanding that rect by [member fit_margin]. This increases both the backbuffer area used and the area covered by the [CanvasGroup] both of which can reduce performance. This should be kept as small as possible and should only be expanded when an increased size is needed (e.g. for custom shader effects).
		</member>
		<member name="use_mipmaps" type="bool" setter="set_use_mipmaps" getter="is_using_mipmaps" default="false">
			If [code]true[/code], calculates mipmaps for the backbuffer before drawing the [CanvasGroup] so that mipmaps can be used in a custom [ShaderMaterial] attached to the [CanvasGroup]. Generating mipmaps has a performance cost so this should not be enabled unless required.
		</member>
	</members>
</class>
